sogno-platform/cimgen

CIMgen.py
build.py
modernpython/Base.py
modernpython/Readme.md
modernpython/__init__.py
modernpython/langPack.py
modernpython/templates/cimpy_class_template.mustache

Adding Python 3.9+ langpack, with pydantic dataclasses.
Those classes cannot be used directly with cimpy, but they do simplify quite a lot of coding. The class tree crawling is built into Base, profiles to which an attribute belongs are added to the attribute definition itself, json dump/parsing is built in. 
Sonarcloud complains about code smells - those are logical, but fixing those would cause discrepancy with the style of the rest of the code, so I leave them as is for now. If that's not the best option, let me know.

Modernpython

---

modernpython/langPack.py
python/langPack.py

Fixing #15. This issue is affecting both python versions.

use float as default for Seconds

---

.devcontainer/Dockerfile.dev
.devcontainer/devcontainer.json
CIMgen.py
Dockerfile
README.md

isAssociationUsed() breaks the cpp and java code generation since the associated langpacks use json.load(). isAssociationUsed() introduces True/False into the json object which is not valid json. In json it would be true/false.
Maybe we should only use dicts and avoid json objects entirely. Changing this attribute to true/false does not work with the mustache template. For now, I included the call to isAssociationUsed() only for modernpython.
I have also added devcontainer files, fixed the dockerfile and updated the README.

include isAssociationUsed() only for modernpython

---

cimgen/cimgen.py
cimgen/languages/cpp/lang_pack.py
cimgen/languages/java/lang_pack.py
cimgen/languages/javascript/lang_pack.py
cimgen/languages/javascript/templates/handlebars_cgmesProfile_template.mustache
cimgen/languages/modernpython/lang_pack.py
cimgen/languages/python/lang_pack.py
cimgen/languages/python/templates/cimpy_cgmesProfile_template.mustache
cimgen/languages/python/templates/cimpy_class_template.mustache

- Add generation of CGMESProfile class (including profile URIs) for python
- Improve generation of CGMESProfile class for javascript
- Add cim namespace to the generated CGMESProfile class
- Add method Profile.uris() to CGMESProfile.py to get the list of profile URIs
- Add recommended class profile to all generated classes (currently only used for python: https://github.com/sogno-platform/cimpy/pull/39)

Add generation of CGMES profile class

---

cimgen/cimgen.py
cimgen/languages/cpp/lang_pack.py
cimgen/languages/java/lang_pack.py
cimgen/languages/javascript/lang_pack.py
cimgen/languages/modernpython/lang_pack.py
cimgen/languages/modernpython/templates/cimpy_class_template.mustache
cimgen/languages/modernpython/utils/chevron_writer.py
cimgen/languages/modernpython/utils/export_template.mustache
cimgen/languages/modernpython/utils/writer.py
cimgen/languages/python/lang_pack.py
pyproject.toml

- Common:
- Fix some attribute types
- Fix handling of Decimal as float class
- Add class property "is_a_primitive_class" and attribute property "is_primitive_float_attribute"
- Improve _get_attribute_type in cimgen.py
- Improve setting of long profile names
- Refactor _merge_profiles and _merge_classes in cimgen.py
- Add "is_a_datatype_class" and "is_datatype_attribute" (stereotype == "CIMDatatype"), use these instead of "is_a_float_class" and "is_primitive_float_attribute"
- modernpython:
- Fix type and default of some attributes (for enums and attribute types Date, DateTime, MonthDay, Status, StreetAddress, StreetDetail, TownDetail)
- Rename writer.py to chevron_writer.py (to prevent conflicts with the new writer in https://github.com/zaphiro-technologies/cimgen/tree/xml-generation-and- …

Fix class and attribute types

---

cimgen/languages/cpp/lang_pack.py
cimgen/languages/cpp/static/BaseClass.cpp
cimgen/languages/cpp/static/BaseClass.hpp
cimgen/languages/cpp/templates/cpp_cgmesProfile_header_template.mustache
cimgen/languages/cpp/templates/cpp_cgmesProfile_object_template.mustache
cimgen/languages/cpp/templates/cpp_header_template.mustache
cimgen/languages/cpp/templates/cpp_object_template.mustache

Only changes for cpp:
- Improve generated classes: add rdfid to BaseClass
- Add generation of CGMESProfile class, add profile URIs and cim namespace
- Add generation of getter functions (this will be used by CIM writer to export CIM data into several files based on CGMES profiles)

Add profile class and writer to cpp

---

cimgen/languages/cpp/lang_pack.py

Revert the commit: "Simplify create_assign function in cpp/lang_pack.py" to prevent cutting of string values at first space in assign methods.

Fix generation of string classes

---

MANIFEST.in
cimgen/languages/cpp/lang_pack.py
cimgen/languages/modernpython/lang_pack.py

- Fix installation of static cpp files
- Fix installation of utils/export_template.mustache for modernpython
- Prevent copying of \_\_pycache__ for modernpython
Bases on branch https://github.com/tom-hg57/cimgen/tree/add-writer-to-java (https://github.com/sogno-platform/cimgen/pull/45)

Fix installation for cpp and modernpython

---

cimgen/build.py
cimgen/cimgen.py
cimgen/languages/cpp/lang_pack.py
cimgen/languages/cpp/templates/cpp_header_template.mustache
cimgen/languages/cpp/templates/cpp_object_template.mustache
cimgen/languages/java/lang_pack.py
cimgen/languages/java/templates/java_class.mustache
cimgen/languages/javascript/lang_pack.py
cimgen/languages/javascript/templates/handlebars_template.mustache
cimgen/languages/modernpython/lang_pack.py
cimgen/languages/modernpython/templates/class_template.mustache
cimgen/languages/modernpython/templates/datatype_template.mustache
cimgen/languages/modernpython/templates/enum_template.mustache
cimgen/languages/modernpython/utils/base.py
cimgen/languages/modernpython/utils/datatypes.py
cimgen/languages/python/lang_pack.py
cimgen/languages/python/templates/cimpy_class_template.mustache

Type annotations make the code easier to understand. It can also be checked with pyright. (Suggestion: check with pyright in pre-commit workflow.)
- Add type annotations to cimgen and all lang_pack.py
- Remove unused functions
- Fix and improve comments 
- Fix ruff warnings for modernpython
- Unify use of partials for cpp, rename lang_pack to langPack
- Rename functions, parameters and variables to fix sonar issues
- Add function get_base_class to all lang_pack.py (replacing dictionary base and function location)
- Simplified template file handling for java, javascript and python

Fix and improve type annotations

---

cimgen/languages/javascript/lang_pack.py

javascript/lang_pack.py tries to remove all unused attributes in run_template(). But removing in a for loop doesn't work. The use of filter fixes this.

Fix unused attributes for javascript

---

cimgen/languages/python/templates/cimpy_class_template.mustache

This PR fixes the recursion error when printing a python CGMES object imported by cimpy as described in https://github.com/sogno-platform/cimpy/issues/10.

fix recursion error when printing python object

---

cimgen/cimgen.py
cimgen/languages/cpp/lang_pack.py
cimgen/languages/java/lang_pack.py
cimgen/languages/java/templates/java_constants.mustache
cimgen/languages/javascript/lang_pack.py
cimgen/languages/modernpython/lang_pack.py
cimgen/languages/modernpython/templates/class_template.mustache
cimgen/languages/modernpython/templates/constants_template.mustache
cimgen/languages/modernpython/templates/enum_template.mustache
cimgen/languages/modernpython/utils/base.py
cimgen/languages/modernpython/utils/chevron_writer.py
cimgen/languages/modernpython/utils/datatypes.py
cimgen/languages/modernpython/utils/export_template.mustache
cimgen/languages/python/lang_pack.py

- add attribute_namespace to json_extra to handle custom attributes
- Fix json_dump error by setting attribute_class as str
- Fix type check errors
- Add default implementation of Base.possible_profiles
- Fix type check warnings in chevron_writer.py - see https://github.com/alliander-opensource/pycgmes/pull/39
- Fix output of bool values in chevron_writer.py (in XML true/false only allowed in lower case) - see https://github.com/alliander-opensource/pycgmes/pull/39
- Add handling of namespaces to chevron_writer.py
- Improve handling of ruff and pyright warnings
- Add version to constants.py for modernpython (needed to test custom namespaces in unit tests)

Fix custom namespaces for modernpython

---

cimgen/languages/cpp/lang_pack.py
cimgen/languages/cpp/templates/cpp_constants_header_template.mustache
cimgen/languages/cpp/templates/cpp_constants_object_template.mustache
cimgen/languages/cpp/templates/cpp_profile_header_template.mustache
cimgen/languages/cpp/templates/cpp_profile_object_template.mustache
cimgen/languages/java/AttributeInterface.java
cimgen/languages/java/BaseClass.java
cimgen/languages/java/BaseClassInterface.java
cimgen/languages/java/lang_pack.py
cimgen/languages/java/templates/java_class.mustache
cimgen/languages/java/utils/RdfReader.java
cimgen/languages/java/utils/RdfWriter.java
cimgen/languages/javascript/lang_pack.py
cimgen/languages/javascript/templates/handlebars_constants_template.mustache
cimgen/languages/javascript/templates/handlebars_profile_template.mustache
cimgen/languages/python/lang_pack.py
cimgen/languages/python/templates/cimpy_constants_template.mustache
cimgen/languages/python/templates/cimpy_profile_template.mustache

- Fix custom namespace in java writer (e.g. "entsoe" in CGMES2, "eu" in CGMES3; using new generated functions getClassNamespaceUrl and getAttributeNamespaceUrl)
- Add version to setup parameters to write it to CimConstants.java (needed to test custom namespaces in unit tests)
- Fix custom namespace in java reader (e.g. entsoe in CGMES2, eu in CGMES3)
- Add version to constants.py for modernpython (needed to test custom namespaces in unit tests)
- Add creation of constants for cpp, generating all namespaces in CimConstants.hpp/cpp; add version to constants for cpp (needed to test custom namespaces in unit tests); remove getCimNamespace() from CGMESProfile.hpp/cpp (use NamespaceMap.at("cim") from CimConstants now)
- Add creation of constants for python, generating all namespaces in …

Fix custom namespaces for java

---

cimgen/languages/java/AttributeInterface.java
cimgen/languages/java/BaseClass.java
cimgen/languages/java/BaseClassBuilder.java
cimgen/languages/java/BaseClassInterface.java
cimgen/languages/java/Boolean.java
cimgen/languages/java/Integer.java
cimgen/languages/java/Logging.java
cimgen/languages/java/PrimitiveBuilder.java
cimgen/languages/java/lang_pack.py
cimgen/languages/java/main/Main.java
cimgen/languages/java/templates/java_class.mustache
cimgen/languages/java/templates/java_classlist.mustache
cimgen/languages/java/templates/java_enum.mustache
cimgen/languages/java/templates/java_float.mustache
cimgen/languages/java/templates/java_string.mustache
cimgen/languages/java/utils/RdfParser.java
cimgen/languages/java/utils/RdfReader.java
cimgen/languages/java/utils/RdfWriter.java

- Change the reader to StAX XMLStreamReader (fixing too long parse time: > 5 hours for 25 MByte, now < 5 seconds :); add consumer function createCimObjectFunction to separate creation of CIM objects from parser code)
- Change the writer to StAX XMLStreamWriter
- Reformat all java sources (replacing tabs with spaces)
- Add generation of CimClassMap.java
- Prevent reader warnings while parsing the model description
- Fix wrong enum namespace in writer (e.g. rdf:resource="http://iec.ch/TC57/CIM100#UnitMultiplier.k" - ignore namespace read from source file - always write attribute namespace of generated enum class)
- Fix reading models from more than one file

Fix long parse time in java reader

---

cimgen/build.py
cimgen/cimgen.py

- Read possible custom profiles in subdirectories of the schema directory (but main directory first)
- Prevent generating classes for ModelDescription and DifferenceModel definitions
- Skip attributes with wrong or missing class in rdf:about

Prepare parsing custom profiles

---

README.md
cimgen/cimgen.py

- Prevent generating classes for ModelDescription and DifferenceModel definitions earlier (to prevent collisions with class DifferenceModel from namespace http://entsoe.eu/ns/nc#)
- Add description how to generate files for custom profiles to Readme.md

Prepare parsing custom profiles - part 2

---

cimgen/languages/java/utils/RdfParser.java
cimgen/languages/java/utils/RdfWriter.java

- Fix reading text with entity references in java reader
- If an XML text value contains entity references the text is splitted into several events and has to be concatenated to get the full text value.
- Some entity references are replaced, like `&lt;` ->`<`, `&gt;` ->`>` etc. and provided as CHARACTERS event.
- Other (unknown) entitity references are provided as ENTITY_REFERENCE event without `&` and `;`.
- Fix null pointer exception in RdfWriter.getAttributeProfile()

Fix entity references in java reader

---

cimgen/languages/java/BaseClass.java
cimgen/languages/java/Logging.java
cimgen/languages/java/lang_pack.py
cimgen/languages/java/main/Main.java
cimgen/languages/java/templates/java_class.mustache
cimgen/languages/java/templates/java_classlist.mustache
cimgen/languages/java/templates/java_enum.mustache
cimgen/languages/java/utils/RdfParser.java
cimgen/languages/java/utils/RdfReader.java
cimgen/languages/java/utils/RdfWriter.java
documentation/CIMgenOverview.md

- Change getter and setter to static functions
- Set cimType and rdfid in BaseClass constructor (fixing this-escape warnings with Java >= 21)
- Remove setter for cimType and rdfid (they are fixed now after creation of a CIM object)
- Fix parsing objects with changing types (e.g. first as Equipment, than as PowerTransformer)
- Add method toString to BaseClass
- Improve logging of unknown attributes in java reader
- Fix parsing objects with overriding attributes
- Add option --log-level to java main program
- Fix collision of label and class_name (e.g. AvailabilitySchedule in profile AvailabilitySchedule)
- Update java in documentation/CIMgenOverview.md
- Add logging of used memory in java reader
- Optimize java writer: iterate over used attributes only
- Fix attribute comments
- Fix …

Improve java

---

cimgen/languages/cpp/static/BaseClass.cpp
cimgen/languages/cpp/static/BaseClass.hpp
cimgen/languages/cpp/static/CimClassDetails.cpp
cimgen/languages/cpp/static/CimClassDetails.hpp
cimgen/languages/cpp/templates/cpp_header_template.mustache
cimgen/languages/cpp/templates/cpp_object_template.mustache

- Fix custom namespace in cpp reader (e.g. entsoe in CGMES2, eu in CGMES3)
- Fix custom namespace in cpp writer (e.g. "entsoe" in CGMES2, "eu" in CGMES3; using new generated functions getClassNamespaceUrl and getAttributeNamespaceUrl)
- Add function isAssignableFrom to fix parsing objects with changing types (e.g. first as Equipment, than as PowerTransformer)

Fix custom namespace for cpp

---

cimgen/cimgen.py
cimgen/languages/cpp/lang_pack.py
cimgen/languages/cpp/templates/cpp_enum_header_template.mustache
cimgen/languages/cpp/templates/cpp_header_template.mustache
cimgen/languages/cpp/templates/cpp_object_template.mustache
cimgen/languages/modernpython/lang_pack.py
cimgen/languages/modernpython/templates/class_template.mustache
cimgen/languages/modernpython/templates/enum_template.mustache
cimgen/languages/python/lang_pack.py
cimgen/languages/python/templates/cimpy_class_template.mustache

- Improve setting of default values for cpp, modernpython and python (generated code is unchanged)
- Remove the unnecessary and misleading copying from muliplicity to dataType (generated code is unchanged) (fixing #28)
- Fix default values for cpp and python
- Change variable name for switch from `_switch` to `switch_` (unified with java)
- Fix attribute and enum comments for cpp
- Fix enum comments for modernpython

Fix default values
